### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by aleixsr** [PepsRyuu/dock-window-preview#4]
I'm getting this:

Error: Failed to install app:
npm WARN config production Use `--omit=dev` instead.
npm ERR! code 1
npm ERR! path /private/var/folders/dl/j_c1x6_538g8dy4gfj5k7fdw0000gn/T/yacakge-ts3UVO/package/node_modules/fetch-yode
npm ERR! command failed
npm ERR! command sh -c -- node lib/install.js
npm ERR! Failed to install Yode Error: Client network socket disconnected before secure TLS connection was established
npm ERR!     at connResetException (node:internal/errors:705:14)
npm ERR!     at TLSSocket.onConnectEnd (node:_tls_wrap:1594:19)
npm ERR!     at TLSSocket.emit (node:events:525:35)
npm ERR!     at endReadableNT (node:internal/streams/readable:1358:12)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   code: 'ECONNRESET',
npm ERR!   path: null,
npm ERR!   host: 'github.com',
npm ERR!   port: 443,
npm ERR!   localAddress: undefined
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asola/.npm/_logs/2023-11-05T06_55_38_478Z-debug-0.log

Please help.

**Comment by PepsRyuu** [comment]
Never seen this one before. Might be a proxy issue? Are you running this on a corporate device or is it your own personal home network?

**Comment by aleixsr** [comment]
Personal network, no proxy in place.

**Comment by aleixsr** [comment]
Tried on another machine with same results.
It happens on "npm install"

**Comment by aleixsr** [comment]
> Tried on another machine with same results. It happens on "npm install"

I think I fixed it running:
`npm install -g npm@10.2.3`
`brew update && brew upgrade`

Now error is:Error: axlib/build/node_gyp_bins/python3: file links out of the package
    at Filesystem.insertLink (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/asar/lib/filesystem.js:98:13)
    at handleFile (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/asar/lib/asar.js:132:20)
    at next (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/asar/lib/asar.js:148:11)
    at next (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/asar/lib/asar.js:149:12)
    at async createAsarArchive (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/yackage/lib/main.js:119:5)
    at async Promise.all (index 0)
    at async packageApp (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/yackage/lib/main.js:187:5)
    at async packageCleanApp (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/yackage/lib/main.js:227:12)
    at async Command.build (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/yackage/bin/yackage.js:32:3)

when running `npm run build`

**Comment by aleixsr** [comment]
Fixed some steps, but again:
`
npm run build                                                     ✔  4780  16:50:25

> dock-window-preview@0.0.5 build
> yackage build out/

Package dir left for debug: /var/folders/08/lqbrp82x29374mhtwdnznf200000gn/T/yacakge-98Wtvj/package
Error: Failed to install app:
npm WARN config production Use `--omit=dev` instead.
npm ERR! code 1
npm ERR! path /private/var/folders/08/lqbrp82x29374mhtwdnznf200000gn/T/yacakge-98Wtvj/package/node_modules/gui
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! Failed to install Yue: Client network socket disconnected before secure TLS connection was established

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asola/.npm/_logs/2023-11-05T15_50_28_990Z-debug-0.log

    at installApp (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/yackage/lib/main.js:76:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async packageCleanApp (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/yackage/lib/main.js:225:20)
    at async Command.build (/Users/asola/Downloads/Hackintosh/dock-window-preview/node_modules/yackage/bin/yackage.js:32:3)`

**Comment by aleixsr** [comment]
Hello? Are you there?

**Comment by PepsRyuu** [comment]
Apologies, life's been a bit busy, so this slipped my mind! 😓

I just retried the quick start installer on my own 2019 Macbook with the latest OS, and it all seems to be working still. The manual steps are also working correctly for me (note that the Node version does matter). 

Don't really think there's anything I can do here since I can't reproduce and it seems like an environment issue of some sort... the quick start script should set up everything you need (correct version of Node etc). Can you provide the complete log of the quick start script?

**Comment by aleixsr** [comment]
Thanks, interesting part starts here:

```
x node-v16.9.1-darwin-x64/bin/npm
++ exportNode
+++ find . -name node
+++ grep bin/node
++ echo ./node/node-v16.9.1-darwin-x64/bin/node
+ NODE=./node/node-v16.9.1-darwin-x64/bin/node
++ exportNpm
+++ find . -name npm-cli.js
+++ grep bin/npm-cli.js
++ echo ./node/node-v16.9.1-darwin-x64/lib/node_modules/npm/bin/npm-cli.js
+ NPM=./node/node-v16.9.1-darwin-x64/lib/node_modules/npm/bin/npm-cli.js
+++ dirname ./node/node-v16.9.1-darwin-x64/bin/node
++ readlink -f ./node/node-v16.9.1-darwin-x64/bin
+ PATH='/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/bin:/Users/asola/.nvm/versions/node/v16.20.2/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public'
+ ./node/node-v16.9.1-darwin-x64/bin/node ./node/node-v16.9.1-darwin-x64/lib/node_modules/npm/bin/npm-cli.js install
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated asar@3.0.3: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm notice
npm notice New major version of npm available! 7.21.1 -> 10.2.4
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.4
npm notice Run npm install -g npm@10.2.4 to update!
npm notice
npm ERR! code 1
npm ERR! path /Users/asola/.dock-window-preview-git/axlib
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.11.6 found at "/usr/local/opt/python@3.11/bin/python3.11"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.9.1/node-v16.9.1-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.9.1/node-v16.9.1-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.9.1/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.9.1/SHASUMS256.txt
npm ERR! (node:9715) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/asola/.dock-window-preview-git/axlib/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/asola/Library/Caches/node-gyp/16.9.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/asola/Library/Caches/node-gyp/16.9.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/asola/Library/Caches/node-gyp/16.9.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/asola/.dock-window-preview-git/axlib',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!              ^^^^^^^^^^^^^^^^^
npm ERR!   File "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!            ^^^^^^^^^^^^^^^^^^
npm ERR!   File "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
npm ERR!     return gyp_main(args)
npm ERR!            ^^^^^^^^^^^^^^
npm ERR!   File "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 629, in gyp_main
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!                                             ^^^^^
npm ERR!   File "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 150, in Load
npm ERR!     result = gyp.input.Load(
npm ERR!              ^^^^^^^^^^^^^^^
npm ERR!   File "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 3021, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 411, in LoadTargetBuildFile
npm ERR!     build_file_data = LoadOneBuildFile(
npm ERR!                       ^^^^^^^^^^^^^^^^^
npm ERR!   File "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 239, in LoadOneBuildFile
npm ERR!     build_file_contents = open(build_file_path, "rU").read()
npm ERR!                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! ValueError: invalid mode: 'rU' while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/bin/node" "/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/asola/.dock-window-preview-git/axlib
npm ERR! gyp ERR! node -v v16.9.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asola/.npm/_logs/2023-11-18T07_55_20_328Z-debug.log
+++ dirname ./node/node-v16.9.1-darwin-x64/bin/node
++ readlink -f ./node/node-v16.9.1-darwin-x64/bin
+ PATH='/Users/asola/.dock-window-preview-git/node/node-v16.9.1-darwin-x64/bin:/Users/asola/.nvm/versions/node/v16.20.2/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public'
+ ./node/node-v16.9.1-darwin-x64/bin/node ./node/node-v16.9.1-darwin-x64/lib/node_modules/npm/bin/npm-cli.js run build

> dock-window-preview@0.0.5 build
> yackage build out/

sh: yackage: command not found
++ git rev-parse --short HEAD
+ COMMIT_ID=f5bb8b9
+ echo f5bb8b9
/bin/bash: line 59: out/Dock Window Preview.app/Contents/Resources/commit_id: No such file or directory
+ tccutil reset Accessibility com.pepsryuu.dock-window-preview
tccutil: No such bundle identifier "com.pepsryuu.dock-window-preview": The operation couldn’t be completed. (OSStatus error -10814.)
+ tccutil reset ScreenCapture com.pepsryuu.dock-window-preview
tccutil: No such bundle identifier "com.pepsryuu.dock-window-preview": The operation couldn’t be completed. (OSStatus error -10814.)
+ echo 'Killing existing process'
Killing existing process
++ ps -e
++ grep 'Dock Window Preview'
++ grep -v grep
++ awk '{print $1}'
+ PID=
+ '[' -z ']'
+ echo 'App not running. Proceeding.'
App not running. Proceeding.
+ cp -r 'out/Dock Window Preview.app' /Users/asola/Applications
cp: out/Dock Window Preview.app: No such file or directory
+ '[' -f .auto-generated ']'
+ echo 'Deleting auto-generated directory'
Deleting auto-generated directory
+ cd /Users/asola
+ rm -rf /Users/asola/.dock-window-preview-git
+ open /Users/asola/Applications
```

**Comment by aleixsr** [comment]
Thanks, let me know if you want I test anything.

**Comment by PepsRyuu** [comment]
I've pushed an update that upgrades to Node 20 (along with all of the necessary fixes due to backwards incompatibilities). Tested it on my own device and it seems to work with Python 3.11. Feel free to give it a try!

**Comment by aleixsr** [comment]
It works now!
Thank you very much.
